### ISSUE TITLE
NPM + CommonJS support

### ISSUE THREAD

**Issue by mbrevda** [timseverien/deep-link.js#10]
Hi! Any chance we can get this published to NPM as well as CommonJS support?

**Comment by timseverien** [comment]
Hey! I’m a bit busy. I would appreciate it if you could help a hand and submit a PR.

**Comment by jt3k** [comment]
+1

**Comment by timseverien** [comment]
How valuable is this, as [this project has become obsolete after the new industry standard](https://github.com/timseverien/deep-link.js/blob/master/README.md#deprecation-notice)?

**Comment by jt3k** [comment]
This is valuable because i have url `<a href="my-mega-app://category">link</a>`on my website and if android-app not installed  user clicking on this link  jumps to "page not found"

As far as i understood the new standard does not include a possibility of replacing deep-link to urls to app-market, or doing other actions.  But your project is able to do it.
