### ISSUE TITLE
Open in new window

### ISSUE THREAD

**Issue by jernejrostan** [timseverien/deep-link.js#4]
Hi, 

Is it possible to workout somehow to open in new window ( on iphone for example) when you click on link. I know that preventDefault prevents to open new window on click if app is not installed.

edit:
well i just remove e.preventDefault() and it works as expected now :)

**Comment by jernejrostan** [comment]
I have allready do some stuff on your code. If you want i can upload?

**Comment by timseverien** [comment]
@jernejrostan You can do a [pull-request](https://help.github.com/articles/using-pull-requests/). As for disabling `e.preventDefault()`, I fear that it may break other functionality. If you have any mobile devices in the area, it would be great if you could do some testing to make sure everything works as expected.

Also, I would like to note [opening things in new tabs/windows with JavaScript](http://stackoverflow.com/questions/4907843/open-a-url-in-a-new-tab-using-javascript) is quite complex, and the likeliness of it being blocked by (native) pop-up blockers is very likely.

I also looked into removing the `e.preventDefault()` line. The default action, which is the link set through the `href` attribute, should only be called if either of the other options (`data-app`/`data-store`) do not work. Given the only real detection is through a timeout, it’s simply a bad solution.

What _does_ work however, is replacing `open(href);` with `el.click();` to simulate a click, instead of changing the href attribute. Try that, and tell me if that solves your problem :)
